# Generated by Django 5.1.15 on 2026-08-09 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_UPDATE', 'Order Update'), ('PAYMENT_UPDATE', 'Payment Update'), ('RETURN_UPDATE', 'Return Update'), ('REFUND_UPDATE', 'Refund Update'), ('PRICE_DROP', 'Price Drop'), ('BACK_IN_STOCK', 'Back In Stock'), ('WISHLIST_UPDATE', 'Wishlist Update'), ('CART_REMINDER', 'Cart Reminder'), ('RECOMMENDATION', 'Recommendation'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True)),
                ('price_drops', models.BooleanField(default=True)),
                ('stock_alerts', models.BooleanField(default=True)),
                ('wishlist_updates', models.BooleanField(default=True)),
                ('cart_reminders', models.BooleanField(default=True)),
                ('recommendations', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
