# Generated by Django 5.1.15 on 2026-08-09 12:45

from django.conf import settings
from django.db import migrations, models
from django.db import connection

def install_trigram(apps, schema_editor):
    if connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

def uninstall_trigram(apps, schema_editor):
    if connection.vendor == 'postgresql':
        schema_editor.execute("DROP EXTENSION IF EXISTS pg_trgm;")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_inventoryreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(install_trigram, uninstall_trigram),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating'], name='catalog_pro_rating_460c72_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant', '-created_at'], name='catalog_pro_merchan_9edaab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
    ]
