# Generated by Django 5.1.15 on 2026-08-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_indexes_and_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('add_to_cart_count', models.PositiveIntegerField(default=0)),
                ('checkout_started_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='catalog.product')),
            ],
        ),
    ]
