# Generated by Django 5.1.15 on 2026-09-04 15:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_reviewhelpfulvote_reviewimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cloudinary_public_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='cloudinary_public_id',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
