services:
  - type: web
    name: nexura-backend
    env: python
    rootDir: Backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com,.vercel.app"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
