# Generated by Django 5.1.15 on 2026-08-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PACKAGING', 'Packaging'), ('TRANSPORTED', 'Transported'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
