# Generated by Django 5.1.15 on 2026-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_returnrequest_refund_supportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
