# Generated by Django 5.1.15 on 2026-09-04 15:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_abandoned_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='evidence_image_url',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='evidence_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
