# Generated by Django 5.1.15 on 2026-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_returnrequest_evidence_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKAGING', 'Packaging'), ('TRANSPORTED', 'Transported'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordereventhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKAGING', 'Packaging'), ('TRANSPORTED', 'Transported'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], max_length=20),
        ),
    ]
